name: AWS ECR EKS
author: Nithin Meppurathu <nithin@nitmedia.com>
description: logs into aws, build and pushes to ecr, allows to run kubectl
branding:
  icon: 'cloud'  
  color: 'red'
inputs:
    AWS_REGION:
      description: The aws region
      required: true
    AWS_ACCESS_KEY_ID:
      description: The aws access id
      required: true
    AWS_SECRET_ACCESS_KEY:
      description: The aws secret key
      required: true
    ECR_REGISTRY: 
      description: The ecr registry
      required: true
    ECR_REPOSITORY:
      description: the erc repo name
      required: false
      default: true
    IMAGE_TAG:
      description: what to build as the image
      required: false
      default: true
    KUBE_CONFIG:
      description: your kube config base64
      required: false
      default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.AWS_REGION }}
    - ${{ inputs.AWS_ACCESS_KEY_ID }}
    - ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    - ${{ inputs.ECR_REGISTRY }}
    - ${{ inputs.ECR_REPOSITORY }}
    - ${{ inputs.IMAGE_TAG }}
    - ${{ inputs.KUBE_CONFIG }}
    
    